# Generated by Django 5.0.7 on 2024-07-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardrobeitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wardrobeitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wardrobe_images/'),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='material',
            field=models.CharField(max_length=100),
        ),
    ]
