# Generated by Django 5.0.7 on 2024-07-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_remove_wardrobeitem_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardrobeitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='wardrobeitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='wardrobeitem',
            name='name',
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='wardrobe_images/'),
            preserve_default=False,
        ),
    ]
